# Generated by Django 3.2.12 on 2022-03-07 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YelpOwned',
            fields=[
                ('business_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('phone_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('price', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('zip_code', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('image_url', models.URLField()),
                ('yelp_url', models.URLField()),
            ],
        ),
    ]
