# Generated by Django 3.2.12 on 2022-03-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_yelpowned'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YelpOwned',
            new_name='YelpRestaurant',
        ),
    ]
