# Generated by Django 3.2.12 on 2022-03-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_yelprestaurant_yelp_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='yelprestaurant',
            name='address',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='yelprestaurant',
            name='name',
            field=models.TextField(default='', max_length=50),
        ),
    ]
