# Generated by Django 3.2.12 on 2022-03-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220325_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelprestaurant',
            name='price',
            field=models.CharField(default='', max_length=5),
        ),
    ]
