# Generated by Django 3.2.12 on 2022-03-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_yelprestaurant_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelprestaurant',
            name='yelp_url',
            field=models.TextField(default='', max_length=500),
        ),
    ]
