# Generated by Django 3.2.12 on 2022-04-04 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YelpRestaurant',
            fields=[
                ('business_id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('name', models.TextField(default='', max_length=50)),
                ('yelp_rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('phone_number', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=30)),
                ('address', models.TextField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=3)),
                ('country', models.CharField(default='', max_length=3)),
                ('zip_code', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('image_url', models.TextField(default='', max_length=200)),
                ('yelp_url', models.TextField(default='', max_length=500)),
            ],
        ),
    ]
