# Generated by Django 3.2.12 on 2022-04-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainabilityRating',
            fields=[
                ('business_id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('all_question_results', models.IntegerField(max_length=76)),
                ('sus_rating', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
