# Generated by Django 3.2.12 on 2022-04-24 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sustainabilityrating_all_question_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='yelprestaurant',
            name='categories_alias',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='yelprestaurant',
            name='categories_title',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='yelprestaurant',
            name='sus_rating',
            field=models.ForeignKey(default='NR', on_delete=django.db.models.deletion.CASCADE, to='app.sustainabilityrating'),
        ),
        migrations.AlterField(
            model_name='sustainabilityrating',
            name='sus_rating',
            field=models.CharField(default='NR', max_length=3),
        ),
    ]
