# Generated by Django 3.2.12 on 2022-04-21 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sustainabilityrating_all_question_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustainabilityrating',
            name='current_question',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(76)]),
        ),
    ]
