# Generated by Django 3.2.12 on 2022-04-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220424_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainabilityrating',
            name='sus_rating',
            field=models.CharField(default='NR', max_length=10),
        ),
    ]
