# Generated by Django 3.2.12 on 2022-04-22 06:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sustainabilityrating_current_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='yelprestaurant',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
