# Generated by Django 3.2.12 on 2022-03-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220309_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='yelprestaurant',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='yelprestaurant',
            name='country',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='yelprestaurant',
            name='state',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='yelprestaurant',
            name='business_id',
            field=models.CharField(max_length=22, primary_key=True, serialize=False),
        ),
    ]
