# Generated by Django 3.2.12 on 2022-04-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_yelprestaurant_sus_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelprestaurant',
            name='categories_alias',
            field=models.TextField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='yelprestaurant',
            name='categories_title',
            field=models.TextField(default='', max_length=50, null=True),
        ),
    ]
