# Generated by Django 3.2.12 on 2022-04-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220424_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelprestaurant',
            name='categories_alias',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='yelprestaurant',
            name='categories_title',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
    ]
