# Generated by Django 3.2.12 on 2022-03-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_yelprestaurant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='yelprestaurant',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='yelprestaurant',
            name='yelp_url',
            field=models.URLField(default=''),
        ),
    ]
