# Generated by Django 3.2.12 on 2022-04-24 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_yelprestaurant_sus_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainabilityrating',
            name='all_question_results',
            field=models.TextField(default=2222222222222222222222222222222222222222222222222222222222222222222222222222222222, max_length=77),
        ),
        migrations.AlterField(
            model_name='yelprestaurant',
            name='sus_rating',
            field=models.ForeignKey(default='NR', on_delete=django.db.models.deletion.PROTECT, to='app.sustainabilityrating'),
        ),
    ]
