# Generated by Django 3.2.12 on 2022-03-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220328_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelprestaurant',
            name='image_url',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='yelprestaurant',
            name='yelp_url',
            field=models.TextField(default='', max_length=200),
        ),
    ]
