# Generated by Django 3.2.12 on 2022-04-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_yelprestaurant_sus_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='yelprestaurant',
            name='distance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=30),
        ),
    ]
