# Generated by Django 3.2.12 on 2022-03-28 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220328_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelprestaurant',
            name='phone_number',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
