# Generated by Django 3.2.12 on 2022-04-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_yelprestaurant_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelprestaurant',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
    ]
