# Generated by Django 3.2.12 on 2022-04-04 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_yelprestaurant_yelp_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
