# Generated by Django 3.2.12 on 2022-04-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_yelpcategories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
